pub mod config;
pub mod daemon;
pub mod error;
pub mod health;
pub mod ipc;
pub mod lifecycle;
pub mod logs;
pub mod manager;
pub mod paths;
pub mod process;
pub mod registry;
pub mod resources;
pub mod restart;
pub mod scheduler;

pub use config::parse_config;
pub use daemon::{DaemonInstance, DaemonSpec, HealthCheckSpec, HealthStatus};
pub use error::{Result, SyspulseError};
pub use lifecycle::LifecycleState;
pub use restart::RestartPolicy;
